FROM rasa/rasa-sdk:3.6.2

USER root
WORKDIR /app
COPY requirements-actions.txt /app/
RUN pip install --no-cache-dir -r requirements-actions.txt
COPY actions/actions.py /app/actions/actions.py
USER 1001

EXPOSE 5055